version: '2'
services:

 py_requests:
    image: linickx/python-alpine-requests
    command: test.py
    volumes:
    - ./:/app/

 py_local:
    build:
      context: ./
      dockerfile: Dockerfile
    command: test.py
    volumes:
    - ./:/app/
